swagger: "2.0"
info: 
  description: Swagger doc for /api/spb/bmc  
  title: Swagger doc for /api/spb/bmc  
  version: 1.0.0
paths: 
  /api/spb/bmc: 
    get: 
      produces: [application/json]
      responses: 
        200: 
          description: ok
          schema: 
            type: object
            additionalProperties: false
            properties: 
              Information: 
                type: object
                additionalProperties: false
                properties: 
                  Reset Reason: 
                    type: string
                  TPM FW version: 
                    type: string
                  TPM TCG version: 
                    type: string
                  Memory Usage: 
                    type: string
                  u-boot version: 
                    type: string
                  vboot: 
                    type: object
                    additionalProperties: true
                    properties: 
                      force_recovery: 
                        type: string
                      cert_time: 
                        type: string
                      cert_fallback_time: 
                        type: string
                      recovery_boot: 
                        type: string
                      uboot_time: 
                        type: string
                      status_crc: 
                        type: string
                      status_text: 
                        type: string
                      tpm_status: 
                        type: string
                      uboot_fallback_time: 
                        type: string
                      software_enforce: 
                        type: string
                      recovery_retried: 
                        type: string
                      hardware_enforce: 
                        type: string
                      status: 
                        type: string
                  CPU Usage: 
                    type: string
                  kernel version: 
                    type: string
                  Secondary Boot Triggered: 
                    type: boolean
                  At-Scale-Debug Running: 
                    type: boolean
                  Description: 
                    type: string
                  uptime: 
                    type: string
                  OpenBMC Version: 
                    type: string
                  open-fds: 
                    type: string
                  load-15: 
                    type: string
                  SPI0 Vendor: 
                    type: string
                  MAC Addr: 
                    type: string
                  memory: 
                    type: object
                    additionalProperties: false
                    properties: 
                      Shmem: 
                        type: number
                        format: int32
                      MemFree: 
                        type: number
                        format: int32
                      MemTotal: 
                        type: number
                        format: int32
                      Cached: 
                        type: number
                        format: int32
                      Buffers: 
                        type: number
                        format: int32
                      MemAvailable: 
                        type: number
                        format: int32
                  SPI1 Vendor: 
                    type: string
                  mmc-info: 
                    type: object
                    format: nullable
                  MTD Parts: 
                    type: array
                    items: 
                      type: string
                  Uptime: 
                    type: string
                  load-1: 
                    type: string
                  load-5: 
                    type: string
              Resources: 
                type: array
                items: 
                  type: string
              Actions: 
                type: array
                items: 
                  type: string
            
