swagger: "2.0"
info: 
  description: Swagger doc for /api/server1/sensors  
  title: Swagger doc for /api/server1/sensors  
  version: 1.0.0
paths: 
  /api/server1/sensors: 
    get: 
      produces: [application/json]
      responses: 
        200: 
          description: ok
          schema: 
            type: object
            additionalProperties: false
            properties: 
              Information: 
                type: object
                additionalProperties: false
                properties: 
                  MB Outlet Temp_T: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB Outlet Temp_B: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB Inlet Temp: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PVDDCR_CPU VR T: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PVDDIO_ABCD VR T: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PVDDIO_EFGH VR T: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PVDDCR_SOC VR T: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SOC Temp: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SOC DIMMA0 Temp: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SOC DIMMC0 Temp: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SOC DIMMD0 Temp: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SOC DIMME0 Temp: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SOC DIMMG0 Temp: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SOC DIMMH0 Temp: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SOC Package Pwr: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PVDDCR_CPU VR P: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PVDDIO_ABCD VR P: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PVDDIO_EFGH VR P: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PVDDCR_SOC VR P: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  P3V3_MB: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  P12V_STBY_MB: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  P1V8_BIC: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  P3V3_STBY_MB: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PV_BAT: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PVPP_ABCD: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PVPP_EFGH: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  P1V8_STBY_BIC: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PVDDCR_CPU VR I: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PVDDIO_ABCD VR I: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PVDDIO_EFGH VR I: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PVDDCR_SOC VR I: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PVDDCR_CPU VR V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PVDDIO_ABCD VR V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PVDDIO_EFGH VR V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PVDDCR_SOC VR V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  INA230 Power: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  INA230 Voltage: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  HOST_BOOT_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
              Actions: 
                type: array
                items: 
                  type: string
              Resources: 
                type: array
                items: 
                  type: string
            