swagger: "2.0"
info: 
  description: Swagger doc for /api/fwinfo  
  title: Swagger doc for /api/fwinfo  
  version: 1.0.0
paths: 
  /api/fwinfo: 
    get: 
      produces: [application/json]
      responses: 
        200: 
          description: ok
          schema: 
            type: object
            additionalProperties: false
            properties: 
              Information: 
                type: object
                additionalProperties: false
                properties: 
                  fruid_info: 
                    type: object
                    additionalProperties: true
                    properties: 
                      slot1: 
                        type: object
                        additionalProperties: false
                        properties: 
                          vendor: 
                            type: string
                          model: 
                            type: string
                          serial_number: 
                            type: string
                          part_number: 
                            type: string
                      nic: 
                        type: object
                        additionalProperties: false
                        properties: 
                          vendor: 
                            type: string
                          model: 
                            type: string
                          serial_number: 
                            type: string
                          part_number: 
                            type: string
                      nicexp: 
                        type: object
                        additionalProperties: false
                        properties: 
                          vendor: 
                            type: object
                            format: nullable
                          model: 
                            type: object
                            format: nullable
                          serial_number: 
                            type: object
                            format: nullable
                          part_number: 
                            type: object
                            format: nullable
                  fw_info: 
                    type: object
                    additionalProperties: true
                    properties: 
                      bmc_ver: 
                        type: string
                      bmc_cpld_ver: 
                        type: object
                        format: nullable
                      bic_version: 
                        type: object
                        format: nullable
              Actions: 
                type: array
                items: 
                  type: string
              Resources: 
                type: array
                items: 
                  type: string
            
